version: 0.2
env:
  secrets-manager:
    AWS_DEFAULT_REGION: my_access_key:AWS_DEFAULT_REGION
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
