version: 0.2

env:
  secrets-manager:
    AWS_DEFAULT_REGION: arn:aws:secretsmanager:us-west-2:193999962471:secret:my_access_key-CQC9vl:AWS_DEFAULT_REGION
    AWS_ACCOUNT_ID: arn:aws:secretsmanager:us-west-2:193999962471:secret:my_access_key-CQC9vl:AWS_ACCOUNT_ID
    IMAGE_REPO_NAME: arn:aws:secretsmanager:us-west-2:193999962471:secret:my_access_key-CQC9vl:IMAGE_REPO_NAME
    IMAGE_TAG: arn:aws:secretsmanager:us-west-2:193999962471:secret:my_access_key-CQC9vl:IMAGE_TAG

phases:
  install:
    runtime-versions:
      # Available settings https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html
      docker: 19
  pre_build:
    commands:
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=193999962471.dkr.ecr.us-west-2.amazonaws.com/test
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=test}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG --build-arg TAG=$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG     
  post_build:
    commands:
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - printf '[{"name":"backend-%s-container","imageUri":"%s"}]' ${DEVELOPMENT_STAGE} $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
