version: 0.2
env:
  secrets-manager:
    AWS_DEFAULT_REGION: om-code-build-secrets:AWS_DEFAULT_REGION
    AWS_ACCOUNT_ID: om-code-build-secrets:AWS_ACCOUNT_ID
    IMAGE_REPO_NAME: om-code-build-secrets:IMAGE_REPO_NAME
    IMAGE_TAG: om-code-build-secrets:IMAGE_TAG
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG --build-arg TAG=$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      
